version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko --version 2.3.0 -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe --version 4.2.3 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  - haxelib install lime 7.9.0
  - RefreshEnv
  - haxelib install openfl
  - haxelib git flixel https://github.com/TheRealJake12/flixel.git
  - haxelib install polymod
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  # haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install flixel-addons
  - haxelib install hxcpp-debug-server
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
  - haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
  - haxelib install actuate 
  - haxelib list

# No tests idk lol
build_script:
  - haxelib run lime build windows
  # haxelib run lime build linux

artifacts:
  - path: export/release/windows/bin
    name: Windows Build
    type: zip
  
